# kustomization.yaml
configMapGenerator:
  - name: test-configmap
    namespace: test-cs3
    behavior: replace
    files:
    - 1.xml
    - 2.html
    options:
      disableNameSuffixHash: true  # Disable the suffix hash
