# kustomization.yaml
configMapGenerator:
  - name: test-configmap-dev
    namespace: test-cs3
    behavior: create
    files:
    - 1.xml
    - 2.html
    - 3.json
    options:
      disableNameSuffixHash: true  # Disable the suffix hash
